web:
  build: ./docker/php
  ports:
    - "8080:80"
  volumes:
    - ./src:/var/www/html
  links:
    - db:db
  environment:
    APP_ENV: dev
db:
  image: mysql
  ports:
    - ":3306"
  volumes:
    - ./docker/mysql/conf.d:/etc/mysql/conf.d
  environment:
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: myapp