app:
  image: debian:jessie
  volumes:
    - ./src:/var/www/html
  tty: true
  container_name: test-app

php:
  build: ./docker/php
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - app
  links:
    - mysql
  container_name: test-web

mysql:
  image: mysql:5.7
  ports:
    - ":3306"
  volumes:
    - ./docker/mysql/conf.d:/etc/mysql/conf.d
  volumes_from:
    - app
  env_file:
    - ./docker/mysql/env.txt
  container_name: test-db